import { createSlice } from "@reduxjs/toolkit";

const initialState = [
  {
    id: 1,
    url: 'https://dl.prokerala.com/downloads/ringtones/files/mp3/john-cena-the-time-is-now-mymp3song-com-19031.mp3',
    title: 'John Cena',
    artist: 'deadmau5',
    album: 'while(1<2)',
    genre: 'Progressive House, Electro House',
    date: '2014-05-20T07:00:00+00:00',
    artwork: 'dfgdfgdffsg',
    duration: 55,
  },
  {
    id: 2,
    url: require('../src/assets/songs/squadGame.mp3'),
    title: 'Squid Game - Mingle Game mp3',
    artist: 'deadmau5',
    artwork: 'ssgsgdsgds',
    duration: 55,
  },
  {
    id: 3,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
   {
    id: 4,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'I Want To Hold Hour Hand - Remastered 2015',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
   {
    id: 5,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
   {
    id: 6,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
   {
    id: 7,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
   {
    id: 8,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
   {
    id: 9,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
   {
    id: 10,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
   {
    id:11,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
   {
    id: 12,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
   {
    id: 13,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
   {
    id: 14,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
   {
    id: 15,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },

   {
    id: 16,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
   {
    id: 17,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
   {
    id: 18,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
   {
    id: 19,
    url: require('../src/assets/songs/GetLow.mp3'),
    title: 'DJ Snake And Dillon Francis x O2Srk.mp3',
    artist: 'deadmau5',
    artwork: 'file:///storage/sdcard0/Downloads/cover.png',
    duration: 233,
  },
];

const TrackSlice = createSlice({
  name: 'track',
  initialState,
  reducers: {
    setAllTrackMusic: (state, action) => {
      return action.payload;
    },
  },
});

export const { setAllTrackMusic } = TrackSlice.actions;
export default TrackSlice.reducer;
